name: remote ssh command
on:  
  schedule:
     - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set current date as env variable
      run: echo "REL::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo $REL
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        #password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.KEY }}
        script: |
          cd ~/test
          whoami
          mkdir release-$REL
          ls -l
